- administrator/components/com_j2store/views/product/tmpl/form_flexivariablevariants.php
> function removeFlexiAllVariant

- administrator/components/com_j2store/library/plugins/payment.php
secrect_key ==> secret_key
Makes it easier long term
> variable name

- administrator/components/com_j2store/controllers/shippingtroubles.php
- administrator/components/com_j2store/views/shippingtroubles/tmpl/default_shipping.php
- administrator/components/com_j2store/views/shippingtroubles/tmpl/default_shipping_product.php
shipping_avaliable => shipping_available
> shipping_avaliable property

- administrator/components/com_j2store/controllers/orders.php
- plugins/content/j2store/j2store.php
> set valid message type

- administrator/components/com_j2store/controllers/productbase.php
- administrator/components/com_j2store/models/behavior/flexivariable.php
- administrator/components/com_j2store/models/behavior/variable.php
- administrator/components/com_j2store/models/variants.php
> function getdimensions

- plugins/j2store/shipping_standard/shipping_standard/tmpl/view.php
> invalid markup

- plugins/j2store/payment_paypal/payment_paypal.php
> function byReference

- modules/admin/j2store_stats/tmpl/default.php
- modules/admin/j2store_stats_mini/tmpl/default.php
> variable tomorrow

- administrator/components/com_j2store/models/shippingtroubles.php
> function buildQuery

- plugins/j2store/app_diagnostics/app_diagnostics.php
> function getJ2storeVersion

- plugins/j2store/report_products/report_products/js/material-charts.js
> variable absoluteHeightMultipler

- administrator/components/com_j2store/models/behavior/flexivariable.php
- administrator/components/com_j2store/models/behavior/variable.php
- administrator/components/com_j2store/views/product/tmpl/form_flexivariablevariants.php
- plugins/j2store/app_flexivariable/app_flexivariable/controller.php
varaint => variant
varient => variant
> 13 variant

- administrator/components/com_j2store/controllers/configurations.php
- components/com_j2store/views/carts/view.html.php
hide_shipping_untill_address_selection => hide_shipping_until_address_selection
> param hide_shipping_untill_address_selection

- administrator/components/com_j2store/helpers/version.php
- plugins/system/j2pagecache/j2pagecache.php
- plugins/system/j2store/j2store.php
- plugins/user/j2userregister/j2userregister.php
Change references from akeeba subscriptions to j2store
> akeebasubs

- administrator/components/com_j2store/models/behavior/configurable.php
- administrator/components/com_j2store/models/behavior/downloadable.php
- administrator/components/com_j2store/models/behavior/flexivariable.php
- administrator/components/com_j2store/models/behavior/simple.php
- administrator/components/com_j2store/models/behavior/variable.php
> array orginal

- plugins/j2store/payment_paypal/payment_paypal.php
In a few places it was set to expresCheckout - this pr changes those to match everywhere else where it is expressCheckout
> expresscheckout

- components/com_j2store/views/products/tmpl/default.xml
This PR re-introduces the menu item title and description, as well as allowing the form to be loaded properly.
> Duplicated attribute 'class' prevents the form to load

- components/com_j2store/views/checkout/tmpl/default.php
Removed + br in jQuery selector
> Removed code preventing error messages to be seen if password issues during registration

- administrator/components/com_j2store/controllers/productbase.php
Use Factory::getContainer()->get('DatabaseDriver'), avoid deprecated.
> Small update to getDbo to getContainer

- script.j2store.php
> Added code to remove the old update server site.

- administrator/components/com_j2store/views/shippingtroubles/tmpl/default_shipping_product.php
#82 accidentably reverted to xhtml style br/
> Revert reintroducing of xhtml

- administrator/components/com_j2store/controllers/traits/list_view.php
> Joomla 5 Name Spacing / Cleanup 

- administrator/components/com_j2store/version.php
- j2store.xml
- media/j2store/css/j2store.css
> [4.0.15] Removed row property that may interfere with layouts

- administrator/components/com_j2store/models/orders.php
optimized search by email address in orders table for sites with large numbers of orders
> Inclusion of #213 into 4.0.16

- administrator/components/com_j2store/helpers/email.php
- administrator/components/com_j2store/helpers/invoice.php
- administrator/components/com_j2store/models/emailtemplates.php
File::getExt does not exist in Joomla\Filesystem\File therefore we need to make sure we call Joomla\CMS\Filesystem\File under Joomla 4
> Ensure File::getExt can be called properly in Joomla 4 AND over

- administrator/components/com_j2store/layouts/joomla/sidebars/submenu.php
- modules/admin/j2store_menu/tmpl/default.php
Also disabled the app store for now
> Add data-menu-key attribute to menu items for easy targeting in guided tours

- administrator/components/com_j2store/sql/install/mysql/install.j2store.sql
- administrator/components/com_j2store/sql/updates/mysql/4.1.0-2025-02-07.sql
- administrator/components/com_j2store/sql/updates/mysql/4.1.0-2025-06-13.sql
- administrator/components/com_j2store/sql/xml/mysql.xml
- administrator/components/com_j2store/sql/xml/mysqli.xml
The install file has been modified to include all alterations present in the xml for sql files.
In Joomla, the install file should contain all the final database queries for new installs.
> Database modifications: decimals (15,5), duplicate queries, ordering and enabled column fixes

- administrator/components/com_j2store/sql/updates/mysql/4.1.0-2025-06-13.sql
and ensured null and defaults remain the same
> Removed the keyword 'COLUMN' to be more universal
